data:
  evfile : Draco.lst
  scfile : ./data/SCfile.fits
  ltcube : Dracolt.fits #Erase this line if you want to generate a new live time cube (it can take a couple hours)

binning:
  roiwidth   : 10.0  #Size of the region of interest (ROI)
  binsz      : 0.1
  binsperdec : 8     #Number of bins per decade of energy

selection :
  emin : 500       #Minimum energy
  emax : 500000    #Maximum energy
  zmax    : 100    #Zenith cut
  evclass : 128
  evtype  : 3
  tmin    : 239557417 # Seconds. In terms of mission elapsed time (MET)
  tmax    : 428903014 # 6 years
  ra: 260.05167
  dec: 57.91528

gtlike:
  edisp : True
  irfs : 'P8R2_SOURCE_V6'
  edisp_disable : ['isodiff','galdiff']

model:
  # Include catalog sources within a box of width roisrc.
  src_roiwidth : 15.0
  
  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v06.fits'
  isodiff  : '$FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_v06.txt'
  # List of catalogs to be used in the model.
  catalogs : ['3FGL']
  sources :
    - { name : 'draco', ra : 260.05167, dec : 57.91528, 
         SpectrumType : 'PowerLaw', Index : 2.0, Prefactor : { 'value' : 0.0, 'scale' : 1e-13 } }
